version: '3.7'
services:
  mongo:
    image: mongo:4.0
    restart: always
    environment:
      # adding users on init results in error
      # https://github.com/docker-library/mongo/issues/323
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: social
    volumes:
      - ./data/mock/mongo:/docker-entrypoint-initdb.d

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_SITE_BASEURL: '/mongo-express/'
    depends_on:
      - mongo

  redis:
    image: 'redis:latest'

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
    depends_on:
      - mongo
      - redis
      - api
      - view

  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
      - /app/node_modules
      - ./api:/app
      - ./data/mock/json:/app/__tests__/mongo-data
      - ./view/src/graphql/queries:/app/__tests__/view-gql-queries
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MONGODB_ADMINUSERNAME: root
      MONGODB_ADMINPASSWORD: example
      AUTH_SECRET: 2323$$%%SS522dkssk

    depends_on:
      - mongo
      - redis
    
    ports:
      - "9229:9229"

  view:
    build:
      dockerfile: Dockerfile.dev
      context: ./view
    volumes:
      - /app/node_modules
      - ./view:/app
